# Generated by Django 4.0.10 on 2024-07-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='ordering',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
