# Generated by Django 4.0.10 on 2024-07-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0002_orderdetail_color_size_ordering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsizecolor',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopp.color'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopp.size'),
        ),
    ]
