# Generated by Django 4.0.10 on 2024-07-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0003_productsizecolor_quantity_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='ordering',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopp.color'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopp.size'),
        ),
        migrations.AlterField(
            model_name='size',
            name='ordering',
            field=models.IntegerField(null=True),
        ),
    ]
