# Generated by Django 4.0.10 on 2024-06-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0003_alter_category_image_alter_order_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
