# Generated by Django 4.0.10 on 2024-07-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0004_color_ordering_alter_orderdetail_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='size',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
