# Generated by Django 4.0.10 on 2024-06-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0004_remove_category_image_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detail_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
