# Generated by Django 4.0.10 on 2024-06-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0005_remove_product_detail_url_remove_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
