# Generated by Django 4.0.10 on 2024-07-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0006_alter_productsizecolor_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizecolor',
            name='quantity_available',
            field=models.PositiveIntegerField(default=-1),
        ),
    ]
