# Generated by Django 4.0.10 on 2024-07-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0008_alter_productsizecolor_quantity_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
