# Generated by Django 4.0.10 on 2024-07-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0009_category_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsizecolor',
            name='quantity_available',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Đặt hàng'), (1, 'Xác nhận'), (2, 'Hủy đơn')], default=0),
        ),
    ]
