# Generated by Django 4.0.10 on 2024-06-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0010_remove_category_code_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
