# Generated by Django 4.0.10 on 2024-07-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0010_remove_productsizecolor_quantity_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'lựa chọn', 'verbose_name_plural': 'lựa chọn'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Màu', 'verbose_name_plural': 'Màu'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'đơn hàng', 'verbose_name_plural': 'đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'chi tiết đơn hàng', 'verbose_name_plural': 'chi tiết đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'sản phẩm', 'verbose_name_plural': 'sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Hình ảnh sản phẩm', 'verbose_name_plural': 'Hình ảnh sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'kích cỡ', 'verbose_name_plural': 'kích cỡ'},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Đặt hàng'), (1, 'Xác nhận')], default=0),
        ),
    ]
