# Generated by Django 4.0.10 on 2024-06-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0012_alter_order_total_price_alter_orderdetail_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='size', to='shopp.category'),
        ),
    ]
