# Generated by Django 4.0.10 on 2024-06-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0013_size_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='sizes', to='shopp.size'),
        ),
    ]
