# Generated by Django 4.0.10 on 2024-06-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0015_remove_order_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ward_id',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
