# Generated by Django 4.0.10 on 2024-06-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0016_remove_order_city_id_remove_order_district_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_id',
            new_name='product',
        ),
    ]
